services:
  - type: web
    name: german-translator-frontend
    env: docker
    dockerfilePath: frontend/Dockerfile
    repo: https://github.com/ShohelAlMahmudDev/AI_German_Translator.git
    rootDir: .  # Critical change
    region: oregon
    plan: free
    branch: main
    envVars:
      - key: PORT
        value: "3000"  # Must match Dockerfile EXPOSE and CMD port
      - key: REACT_APP_BACKEND_URL
        value: https://german-translator-backend.onrender.com
        sync: false
    healthCheckPath: /
    autoDeploy: true
  - type: web
    name: german-translator-backend
    env: docker
    dockerfilePath: backend/Dockerfile
    repo: https://github.com/ShohelAlMahmudDev/AI_German_Translator.git
    rootDir: .  # Root of repository
    region: oregon
    plan: free
    branch: main
    envVars:
      - key: DEEPSEEK_API_KEY
        sync: false
      - key: DEEPSEEK_API_URL
        sync: false
      - key: PORT
        value: 10000
    healthCheckPath: /docs
    autoDeploy: true
    numInstances: 1