services:
  - type: web
    name: german-translator-frontend
    env: docker
    dockerfilePath: ./frontend/Dockerfile  # Updated to frontend/
    repo: https://github.com/ShohelAlMahmudDev/AI_German_Translator.git
    rootDir: frontend                      # Updated to frontend/
    startCommand: serve -s build -l 10000
    region: oregon
    plan: free
    branch: main
    healthCheckPath: /
    autoDeploy: true
    numInstances: 1

  - type: web
    name: german-translator-backend
    env: docker
    dockerfilePath: ./backend/Dockerfile
    repo: https://github.com/ShohelAlMahmudDev/AI_German_Translator.git
    rootDir: backend
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    region: oregon
    plan: free
    branch: main
    envVars:
      - key: DEEPSEEK_API_KEY
        sync: false  # Set manually in dashboard
    healthCheckPath: /docs
    autoDeploy: true
    numInstances: 1