services:
  - type: web
    name: german-translator-frontend
    env: docker
    dockerfilePath: ./frontend/Dockerfile
    repo: https://github.com/ShohelAlMahmudDev/AI_German_Translator.git
    rootDir: frontend
    region: oregon
    plan: free
    branch: main
    healthCheckPath: /
    autoDeploy: true
    numInstances: 1
    envVars:
      - key: REACT_APP_BACKEND_URL
        value: https://german-translator-backend.onrender.com
        sync: false
    buildCommand: npm install && npm run build
    staticPublishPath: ./build  # Changed from dist to build (standard React output)

  - type: web
    name: german-translator-backend
    env: docker
    dockerfilePath: ./backend/Dockerfile
    repo: https://github.com/ShohelAlMahmudDev/AI_German_Translator.git
    rootDir: backend
    region: oregon
    plan: free
    branch: main
    envVars:
      - key: DEEPSEEK_API_KEY
        sync: false
      - key: DEEPSEEK_API_URL
        sync: false
      - key: PORT
        value: 10000
    healthCheckPath: /docs
    autoDeploy: true
    numInstances: 1