services:
  - type: web
    name: german-translator-frontend
    env: docker
    repo: https://github.com/ShohelAlMahmudDev/AI_German_Translator.git
    rootDir: chatbot-ui
    buildCommand: docker build -f Dockerfile -t german-translator-frontend .
    startCommand: serve -s build -l 10000
    region: oregon
    plan: free
    branch: main
    healthCheckPath: /
    autoDeploy: true

  - type: web
    name: german-translator-backend
    env: docker
    repo: https://github.com/ShohelAlMahmudDev/AI_German_Translator.git
    rootDir: backend
    buildCommand: docker build -f Dockerfile -t german-translator-backend .
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    region: oregon
    plan: free
    branch: main
    envVars:
      - key: DEEPSEEK_API_KEY
      - key: DEEPSEEK_API_URL
        sync: false  # Set manually in Render dashboard
    healthCheckPath: /docs
    autoDeploy: true