services:
  - type: web
    name: german-translator-frontend
    env: docker
    repo: https://github.com/ShohelAlMahmudDev/AI_German_Translator.git
    buildCommand: docker build -f chatbot-ui/Dockerfile -t german-translator-frontend .
    startCommand: serve -s build -l 10000  # Changed to 10000 for Render
    region: oregon
    plan: free
    branch: main
    healthCheckPath: /

  - type: web
    name: german-translator-backend
    env: docker
    repo: https://github.com/ShohelAlMahmudDev/AI_German_Translator.git
    buildCommand: docker build -f backend/Dockerfile -t german-translator-backend .
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000  # Changed to 10000 for Render
    region: oregon
    plan: free
    branch: main
    envVars:
      - key: DEEPSEEK_API_KEY
        sync: false # Set manually in dashboard
    healthCheckPath: /docs